server:
  port: 8820
spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mapping/**/*.xml
